.TH "Animation::Frame" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animation::Frame
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Rectangle \fBrect\fP"
.br
.ti -1c
.RI "Vector2 \fBorigin\fP"
.br
.ti -1c
.RI "Vector2 \fBscale\fP"
.br
.ti -1c
.RI "float \fBrotation\fP"
.br
.ti -1c
.RI "Color \fBcolor\fP"
.br
.ti -1c
.RI "bool \fBflipX\fP"
.br
.ti -1c
.RI "bool \fBflipY\fP"
.br
.ti -1c
.RI "float \fBduration\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
