.TH "AudioSource" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioSource
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBecs::Component< AudioSource >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP (int entityID)"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "void \fBOnAddComponent\fP (int entityID)"
.br
.ti -1c
.RI "void \fBAddMusicName\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBAddSoundName\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBRmMusicName\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBRmSoundName\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBAddMusic\fP (const std::string &name, const std::string &path)"
.br
.ti -1c
.RI "void \fBAddSound\fP (const std::string &name, const std::string &path)"
.br
.ti -1c
.RI "template<typename T > void \fBStop\fP (const std::string &name)"
.br
.ti -1c
.RI "template<typename T > void \fBPause\fP (const std::string &name)"
.br
.ti -1c
.RI "template<typename T > void \fBResume\fP (const std::string &name)"
.br
.ti -1c
.RI "template<typename T > void \fBDelete\fP (const std::string &name)"
.br
.ti -1c
.RI "template<typename T > void \fBSetVolume\fP (const std::string &name, float volume)"
.br
.ti -1c
.RI "void \fBSetGlobalVolume\fP (float volume)"
.br
.ti -1c
.RI "template<typename T > bool \fBIsPlaying\fP (const std::string &name)"
.br
.ti -1c
.RI "float \fBGetMusicTPlayed\fP (const std::string &name)"
.br
.ti -1c
.RI "float \fBGetMusicTLength\fP (const std::string &name)"
.br
.ti -1c
.RI "template<typename T > void \fBPlay\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBPlay\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBPlay\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBStop\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBStop\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBPause\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBPause\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBResume\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBResume\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBDelete\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBDelete\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> void \fBSetVolume\fP (const std::string &name, float volume)"
.br
.ti -1c
.RI "template<> void \fBSetVolume\fP (const std::string &name, float volume)"
.br
.ti -1c
.RI "template<> bool \fBIsPlaying\fP (const std::string &name)"
.br
.ti -1c
.RI "template<> bool \fBIsPlaying\fP (const std::string &name)"
.br
.in -1c

Public Member Functions inherited from \fBecs::Component< AudioSource >\fP
.in +1c
.ti -1c
.RI "void \fBUpdate\fP (int entityID)"
.br
.RI "This is played every frame\&. "
.ti -1c
.RI "void \fBStart\fP ()"
.br
.RI "This is played once at the start of the game\&. "
.ti -1c
.RI "void \fBLoad\fP (const std::string &path)"
.br
.RI "This is played when the components is to be loaded from a file\&. "
.ti -1c
.RI "void \fBSave\fP (const std::string &path)"
.br
.RI "This is to be played when the component is to be saved to a file\&. "
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.RI "This is to be played when the component is loaded (not necessarily from a file)\&. "
.ti -1c
.RI "void \fBOnAddComponent\fP (int entityID)"
.br
.RI "This function is called once when the component is added to an entity\&. "
.ti -1c
.RI "std::map< std::string, metadata_t > \fBGetMetadata\fP ()"
.br
.ti -1c
.RI "std::string \fBGetClassName\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "serialize std::vector< std::string > \fB_music_List_Name\fP"
.br
.ti -1c
.RI "serialize std::vector< std::string > \fB_sound_List_Name\fP"
.br
.ti -1c
.RI "std::map< std::string, std::shared_ptr< Music > > \fB_music_List\fP"
.br
.ti -1c
.RI "std::map< std::string, std::shared_ptr< Sound > > \fB_sound_List\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
