.TH "AUserComponent" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AUserComponent \- This class brings back classical inheritance to the ECS to allow runtime polymorphism in the editor, so that the user can write his / her own scripts\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UserComponentWrapper\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBUpdate\fP (int entityID)=0"
.br
.RI "This function is called every frame\&. It is the main function of the script\&. "
.ti -1c
.RI "virtual void \fBStart\fP ()=0"
.br
.RI "This function is called once before the first frame of the game\&. It does not get called if the game has already started\&. "
.ti -1c
.RI "virtual void \fBOnLoad\fP ()"
.br
.RI "This function is called once, the first time that this class will be loaded into the engine\&. "
.ti -1c
.RI "virtual void \fBOnAddComponent\fP (int entityID)"
.br
.RI "This function is called everytime a component is added to an entity\&. "
.ti -1c
.RI "virtual void \fBLoad\fP (const std::string &path)=0"
.br
.RI "This function loads the data from the file at the given path\&. "
.ti -1c
.RI "virtual void \fBSave\fP (const std::string &path)=0"
.br
.RI "This function saves the data to the file at the given path\&. "
.ti -1c
.RI "virtual std::string \fBGetClassName\fP () const =0"
.br
.RI "Returns a string representing the name of the class in a human-readable format\&. "
.ti -1c
.RI "virtual std::map< std::string, metadata_t > \fBGetMetadata\fP ()=0"
.br
.RI "Returns the metadata of the class\&. The metadata contains information about the members of the class\&. (see metadata\&.h for more information) "
.in -1c
.SH "Detailed Description"
.PP 
This class brings back classical inheritance to the ECS to allow runtime polymorphism in the editor, so that the user can write his / her own scripts\&. 


.SH "Member Function Documentation"
.PP 
.SS "virtual std::string AUserComponent::GetClassName () const\fC [pure virtual]\fP"

.PP
Returns a string representing the name of the class in a human-readable format\&. 
.PP
\fBReturns\fP
.RS 4
std::string 
.RE
.PP

.SS "virtual std::map< std::string, metadata_t > AUserComponent::GetMetadata ()\fC [pure virtual]\fP"

.PP
Returns the metadata of the class\&. The metadata contains information about the members of the class\&. (see metadata\&.h for more information) 
.PP
\fBReturns\fP
.RS 4
std::map<std::string, metadata_t> 
.RE
.PP

.SS "virtual void AUserComponent::Load (const std::string & path)\fC [pure virtual]\fP"

.PP
This function loads the data from the file at the given path\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP

.SS "virtual void AUserComponent::OnAddComponent (int entityID)\fC [inline]\fP, \fC [virtual]\fP"

.PP
This function is called everytime a component is added to an entity\&. 
.PP
\fBWarning\fP
.RS 4
This function is not generated automatically and must be implemented by the user\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIentityID\fP 
.RE
.PP

.SS "virtual void AUserComponent::OnLoad ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
This function is called once, the first time that this class will be loaded into the engine\&. 
.PP
\fBWarning\fP
.RS 4
This function is not generated automatically and must be implemented by the user\&. 
.RE
.PP

.SS "virtual void AUserComponent::Save (const std::string & path)\fC [pure virtual]\fP"

.PP
This function saves the data to the file at the given path\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP

.SS "virtual void AUserComponent::Start ()\fC [pure virtual]\fP"

.PP
This function is called once before the first frame of the game\&. It does not get called if the game has already started\&. 
.PP
\fBWarning\fP
.RS 4
This function is not generated automatically and must be implemented by the user\&. 
.RE
.PP

.SS "virtual void AUserComponent::Update (int entityID)\fC [pure virtual]\fP"

.PP
This function is called every frame\&. It is the main function of the script\&. 
.PP
\fBWarning\fP
.RS 4
This function is not generated automatically and must be implemented by the user\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIentityID\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
