.TH "Collider2D" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collider2D \- A Polygon collider class for 2D entities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Collider2D\&.hpp>\fP
.PP
Inherits \fBecs::Component< Collider2D >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP (int entityID)"
.br
.ti -1c
.RI "void \fBOnAddComponent\fP (int entityID)"
.br
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "int \fBGetEntityID\fP () const"
.br
.ti -1c
.RI "void \fBAddVertices\fP (std::vector< float > vertices)"
.br
.RI "Adds a set of vertices to the collider\&. "
.ti -1c
.RI "const std::vector< \fBgraph::vec2f\fP > & \fBGetEdges\fP () const noexcept"
.br
.RI "Returns the list of edges of the collider\&. "
.ti -1c
.RI "const std::vector< \fBgraph::vec2f\fP > & \fBGetNormals\fP () const noexcept"
.br
.RI "Returns the list of normals of the collider\&. "
.ti -1c
.RI "const std::vector< float > & \fBGetVertices\fP () const noexcept"
.br
.RI "Returns the list of vertices of the collider\&. "
.ti -1c
.RI "std::vector< float > & \fBGetVerticesMutable\fP () noexcept"
.br
.RI "returns the vertices in a mutable way\&. (reference) "
.ti -1c
.RI "bool \fBIsColliding\fP () const noexcept"
.br
.RI "Returns true if the collider has a collision with another collider\&. This gets reset every frame\&. "
.ti -1c
.RI "void \fBDebugDraw\fP () const"
.br
.RI "Draws the edges of the collider if the editor mode is set\&. "
.ti -1c
.RI "void \fBSetTag\fP (std::string tag) noexcept"
.br
.RI "Sets the tag of the collider\&. "
.ti -1c
.RI "std::string \fBGetTag\fP () const noexcept"
.br
.RI "Returns the tag of the collider\&. "
.ti -1c
.RI "void \fBSetLayer\fP (std::string layer) noexcept"
.br
.RI "Sets the layer of the collider\&. "
.ti -1c
.RI "std::string \fBGetLayer\fP () const noexcept"
.br
.RI "Returns the layer of the collider\&. "
.ti -1c
.RI "void \fBIgnoreLayer\fP (std::string layer) noexcept"
.br
.RI "Ignore this layer when checking for collisions\&. "
.ti -1c
.RI "std::vector< std::string > \fBGetIgnoredLayers\fP () const noexcept"
.br
.RI "Returns the list of layers the collider is ignoring\&. "
.ti -1c
.RI "void \fBSetOnCollisionEnter\fP (std::function< void(int, int)> callback)"
.br
.RI "Sets the callback that gets called when the entity enters a collision\&. "
.ti -1c
.RI "void \fBSetOnCollisionExit\fP (std::function< void(int)> callback)"
.br
.RI "Sets the callback that gets called when the entity exits a collision\&. "
.ti -1c
.RI "std::vector< float > \fBGetVerticesWithPosition\fP () const noexcept"
.br
.RI "Returns the vertices update with the position from the collider\&. "
.in -1c

Public Member Functions inherited from \fBecs::Component< Collider2D >\fP
.in +1c
.ti -1c
.RI "void \fBUpdate\fP (int entityID)"
.br
.RI "This is played every frame\&. "
.ti -1c
.RI "void \fBStart\fP ()"
.br
.RI "This is played once at the start of the game\&. "
.ti -1c
.RI "void \fBLoad\fP (const std::string &path)"
.br
.RI "This is played when the components is to be loaded from a file\&. "
.ti -1c
.RI "void \fBSave\fP (const std::string &path)"
.br
.RI "This is to be played when the component is to be saved to a file\&. "
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.RI "This is to be played when the component is loaded (not necessarily from a file)\&. "
.ti -1c
.RI "void \fBOnAddComponent\fP (int entityID)"
.br
.RI "This function is called once when the component is added to an entity\&. "
.ti -1c
.RI "std::map< std::string, metadata_t > \fBGetMetadata\fP ()"
.br
.ti -1c
.RI "std::string \fBGetClassName\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Polygon collider class for 2D entities\&. 


.SH "Member Function Documentation"
.PP 
.SS "void Collider2D::DebugDraw () const"

.PP
Draws the edges of the collider if the editor mode is set\&. 
.SS "const std::vector< \fBgraph::vec2f\fP > & Collider2D::GetEdges () const\fC [noexcept]\fP"

.PP
Returns the list of edges of the collider\&. 
.SS "std::vector< std::string > Collider2D::GetIgnoredLayers () const\fC [noexcept]\fP"

.PP
Returns the list of layers the collider is ignoring\&. 
.SS "std::string Collider2D::GetLayer () const\fC [noexcept]\fP"

.PP
Returns the layer of the collider\&. 
.SS "const std::vector< \fBgraph::vec2f\fP > & Collider2D::GetNormals () const\fC [noexcept]\fP"

.PP
Returns the list of normals of the collider\&. 
.SS "std::string Collider2D::GetTag () const\fC [noexcept]\fP"

.PP
Returns the tag of the collider\&. 
.SS "const std::vector< float > & Collider2D::GetVertices () const\fC [noexcept]\fP"

.PP
Returns the list of vertices of the collider\&. 
.SS "std::vector< float > & Collider2D::GetVerticesMutable ()\fC [noexcept]\fP"

.PP
returns the vertices in a mutable way\&. (reference) 
.SS "std::vector< float > Collider2D::GetVerticesWithPosition () const\fC [noexcept]\fP"

.PP
Returns the vertices update with the position from the collider\&. 
.SS "void Collider2D::IgnoreLayer (std::string layer)\fC [noexcept]\fP"

.PP
Ignore this layer when checking for collisions\&. 
.SS "bool Collider2D::IsColliding () const\fC [noexcept]\fP"

.PP
Returns true if the collider has a collision with another collider\&. This gets reset every frame\&. 
.SS "void Collider2D::SetLayer (std::string layer)\fC [noexcept]\fP"

.PP
Sets the layer of the collider\&. 
.SS "void Collider2D::SetOnCollisionEnter (std::function< void(int, int)> callback)"

.PP
Sets the callback that gets called when the entity enters a collision\&. 
.SS "void Collider2D::SetOnCollisionExit (std::function< void(int)> callback)"

.PP
Sets the callback that gets called when the entity exits a collision\&. 
.SS "void Collider2D::SetTag (std::string tag)\fC [noexcept]\fP"

.PP
Sets the tag of the collider\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
