.TH "ecs::IController" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecs::IController \- This interface is used to define a controller, meaning a class that will be used to control an entity\&. It will expose the directives from the player / ai / network so that they are accessible from the entity\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IController\&.hpp>\fP
.PP
Inherited by \fBecs::AController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::vector< std::string > & \fBGetDirectives\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBPollDirectives\fP ()=0"
.br
.RI "Updates the state of the directives, either from the local player, the network, or the ai\&. "
.ti -1c
.RI "virtual void \fBUpdatePipeline\fP ()=0"
.br
.RI "Should insert the controller in the engine's pipeline, before the --Update-- routine\&. "
.ti -1c
.RI "virtual void \fBSetEntity\fP (int entityID)=0"
.br
.RI "Sets the internal reference to the entity's controller\&. "
.in -1c
.SH "Detailed Description"
.PP 
This interface is used to define a controller, meaning a class that will be used to control an entity\&. It will expose the directives from the player / ai / network so that they are accessible from the entity\&. 


.SH "Member Function Documentation"
.PP 
.SS "virtual void ecs::IController::PollDirectives ()\fC [pure virtual]\fP"

.PP
Updates the state of the directives, either from the local player, the network, or the ai\&. 
.PP
Implemented in \fBecs::AController\fP\&.
.PP
\fBExamples\fP
.in +1c
\fB/home/amour/Documents/epitech/rtype/ecs/include/IController\&.hpp\fP\&.
.SS "virtual void ecs::IController::SetEntity (int entityID)\fC [pure virtual]\fP"

.PP
Sets the internal reference to the entity's controller\&. 
.PP
Implemented in \fBecs::AController\fP\&.
.PP
\fBExamples\fP
.in +1c
\fB/home/amour/Documents/epitech/rtype/ecs/include/IController\&.hpp\fP\&.
.SS "virtual void ecs::IController::UpdatePipeline ()\fC [pure virtual]\fP"

.PP
Should insert the controller in the engine's pipeline, before the --Update-- routine\&. 
.PP
Implemented in \fBecs::AController\fP\&.
.PP
\fBExamples\fP
.in +1c
\fB/home/amour/Documents/epitech/rtype/ecs/include/IController\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
