.TH "ecs::AController" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecs::AController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBecs::IController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::vector< std::string > & \fBGetDirectives\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBPollDirectives\fP ()=0"
.br
.RI "Updates the state of the directives, either from the local player, the network, or the ai\&. "
.ti -1c
.RI "void \fBUpdatePipeline\fP () override"
.br
.RI "Should insert the controller in the engine's pipeline, before the --Update-- routine\&. "
.ti -1c
.RI "void \fBSetEntity\fP (int entityID) override"
.br
.RI "Sets the internal reference to the entity's controller\&. "
.in -1c
.in +1c
.ti -1c
.RI "virtual std::vector< std::string > & \fBGetDirectives\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBPollDirectives\fP ()=0"
.br
.RI "Updates the state of the directives, either from the local player, the network, or the ai\&. "
.ti -1c
.RI "virtual void \fBUpdatePipeline\fP ()=0"
.br
.RI "Should insert the controller in the engine's pipeline, before the --Update-- routine\&. "
.ti -1c
.RI "virtual void \fBSetEntity\fP (int entityID)=0"
.br
.RI "Sets the internal reference to the entity's controller\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fB_entity\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual std::vector< std::string > & ecs::AController::GetDirectives ()\fC [pure virtual]\fP"

.PP
Implements \fBecs::IController\fP\&.
.SS "virtual void ecs::AController::PollDirectives ()\fC [pure virtual]\fP"

.PP
Updates the state of the directives, either from the local player, the network, or the ai\&. 
.PP
Implements \fBecs::IController\fP\&.
.PP
\fBExamples\fP
.in +1c
\fB/home/amour/Documents/epitech/rtype/ecs/include/IController\&.hpp\fP\&.
.SS "void ecs::AController::SetEntity (int entityID)\fC [override]\fP, \fC [virtual]\fP"

.PP
Sets the internal reference to the entity's controller\&. 
.PP
Implements \fBecs::IController\fP\&.
.PP
\fBExamples\fP
.in +1c
\fB/home/amour/Documents/epitech/rtype/ecs/include/IController\&.hpp\fP\&.
.SS "void ecs::AController::UpdatePipeline ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Should insert the controller in the engine's pipeline, before the --Update-- routine\&. 
.PP
Implements \fBecs::IController\fP\&.
.PP
\fBExamples\fP
.in +1c
\fB/home/amour/Documents/epitech/rtype/ecs/include/IController\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
