.TH "ecs::AActor" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecs::AActor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBecs::IActor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPossess\fP (int entity, std::shared_ptr< \fBIController\fP > controller) override"
.br
.in -1c
.in +1c
.ti -1c
.RI "virtual void \fBPossess\fP (int entity, std::shared_ptr< \fBIController\fP >)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBIController\fP > \fB_controller\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ecs::AActor::Possess (int entity, std::shared_ptr< \fBIController\fP > controller)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBecs::IActor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
