.TH "ecs::ECS< VanillaComponents >::InfoStream" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecs::ECS< VanillaComponents >::InfoStream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBInfoStream\fP & \fBoperator<<\fP (const T &t)"
.br
.ti -1c
.RI "\fBInfoStream\fP & \fBoperator<<\fP (std::ostream &(*f)(std::ostream &))"
.br
.ti -1c
.RI "template<typename T > \fBInfoStream\fP & \fBoperator<<\fP (const T &t)"
.br
.ti -1c
.RI "\fBInfoStream\fP & \fBoperator<<\fP (std::ostream &(*f)(std::ostream &))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
