.TH "ecs::IActor" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecs::IActor \- This class is used to define an actor, meaning an entity that can be controlled by a controller (player, ai, network, etc\&.)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IActor\&.hpp>\fP
.PP
Inherited by \fBecs::AActor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBPossess\fP (int entity, std::shared_ptr< \fBIController\fP >)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to define an actor, meaning an entity that can be controlled by a controller (player, ai, network, etc\&.) 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
