.TH "eng::IGame" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eng::IGame \- Interface for the game class, which shall be loaded dynamically by the engine\&. The classes inheriting from this interface will be given an occasion to initialize their specific functionalities, as well as do some cleanup when the game is unloaded\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IGame\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBInit\fP (\fBEngine\fP *)=0"
.br
.RI "Called when the game is loaded by the engine\&. "
.ti -1c
.RI "virtual void \fBCleanup\fP (\fBEngine\fP *)=0"
.br
.RI "Called when the game is unloaded by the engine\&. "
.ti -1c
.RI "virtual bool \fBIsOnLine\fP (\fBEngine\fP *)=0"
.br
.RI "Returns true if the game is online, false otherwise\&. If it returns true, the engine will call the WaitForPlayers method before launching the game\&. "
.ti -1c
.RI "virtual void \fBWaitConnect\fP (\fBEngine\fP *)=0"
.br
.RI "Called when the game is online, before the game is launched\&. "
.ti -1c
.RI "virtual void \fBLoadFirstScene\fP (\fBEngine\fP *)=0"
.br
.RI "Is called to allow the game to load its first scene\&. "
.ti -1c
.RI "virtual void \fBPreSceneInstantiationHook\fP (\fBEngine\fP *, const std::string &sceneName)=0"
.br
.RI "Pre-scene instantiation, called after each scene is loaded in the engine, but before it is displayed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface for the game class, which shall be loaded dynamically by the engine\&. The classes inheriting from this interface will be given an occasion to initialize their specific functionalities, as well as do some cleanup when the game is unloaded\&. 


.SH "Member Function Documentation"
.PP 
.SS "virtual void eng::IGame::Cleanup (\fBEngine\fP *)\fC [pure virtual]\fP"

.PP
Called when the game is unloaded by the engine\&. 
.SS "virtual void eng::IGame::Init (\fBEngine\fP *)\fC [pure virtual]\fP"

.PP
Called when the game is loaded by the engine\&. 
.SS "virtual bool eng::IGame::IsOnLine (\fBEngine\fP *)\fC [pure virtual]\fP"

.PP
Returns true if the game is online, false otherwise\&. If it returns true, the engine will call the WaitForPlayers method before launching the game\&. 
.SS "virtual void eng::IGame::LoadFirstScene (\fBEngine\fP *)\fC [pure virtual]\fP"

.PP
Is called to allow the game to load its first scene\&. 
.SS "virtual void eng::IGame::PreSceneInstantiationHook (\fBEngine\fP *, const std::string & sceneName)\fC [pure virtual]\fP"

.PP
Pre-scene instantiation, called after each scene is loaded in the engine, but before it is displayed\&. 
.SS "virtual void eng::IGame::WaitConnect (\fBEngine\fP *)\fC [pure virtual]\fP"

.PP
Called when the game is online, before the game is launched\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
