.TH "eng::SceneBuffer" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eng::SceneBuffer \- A class to contain a scene while it is being loaded\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SceneManager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneBuffer\fP (const std::string &sceneName, \fBEngine\fP &engine)"
.br
.RI "Construct a new Scene Buffer object and loads the scene in the background\&. When the scene is ready, it sets the _isReady flag to true\&. "
.ti -1c
.RI "bool \fBIsReady\fP () const"
.br
.RI "Returns true if the scene is ready to be used, false otherwise\&. "
.ti -1c
.RI "ecs::ECSImpl::AllCpt & \fBGetComponents\fP ()"
.br
.RI "Returns the components of the scene\&. "
.in -1c
.SH "Detailed Description"
.PP 
A class to contain a scene while it is being loaded\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "eng::SceneBuffer::SceneBuffer (const std::string & sceneName, \fBEngine\fP & engine)"

.PP
Construct a new Scene Buffer object and loads the scene in the background\&. When the scene is ready, it sets the _isReady flag to true\&. 
.PP
\fBParameters\fP
.RS 4
\fIsceneName\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "ecs::ECSImpl::AllCpt & eng::SceneBuffer::GetComponents ()"

.PP
Returns the components of the scene\&. 
.PP
\fBReturns\fP
.RS 4
ECSImpl::AllCpt 
.RE
.PP

.SS "bool eng::SceneBuffer::IsReady () const"

.PP
Returns true if the scene is ready to be used, false otherwise\&. 
.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
