.TH "eng::CompatibilityException" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eng::CompatibilityException
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompatibilityException\fP (const std::string &msg)"
.br
.RI "Signals the fact that the current plugin is not compatible with one of the settings of the engine\&. "
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eng::CompatibilityException::CompatibilityException (const std::string & msg)\fC [inline]\fP"

.PP
Signals the fact that the current plugin is not compatible with one of the settings of the engine\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
