.TH "eng::Engine::Options" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eng::Engine::Options
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::string \fBEDITOR\fP = '\-\-editor'"
.br
.ti -1c
.RI "static const std::string \fBGAME\fP = 'game'"
.br
.ti -1c
.RI "static const std::string \fBCONFIG_DIR\fP = '\-\-config\-dir'"
.br
.ti -1c
.RI "static const std::string \fBVERBOSE\fP = '\-\-verbose'"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
