.TH "eng::SceneManager" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eng::SceneManager \- Singleton for the scene manager, which can be used to load scenes in the background and switch between them\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SceneManager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneManager\fP (\fBEngine\fP &engine)"
.br
.ti -1c
.RI "void \fBInitEditorMode\fP ()"
.br
.RI "Inits the editor mode of the scenemanager to allow for manual commands\&. "
.ti -1c
.RI "void \fBLoadSceneAsync\fP (const std::string &sceneName)"
.br
.RI "Loads a scene in the background\&. "
.ti -1c
.RI "void \fBSwitchScene\fP (const std::string &sceneName)"
.br
.RI "switches the current scene to the one specified "
.ti -1c
.RI "void \fBUnloadScene\fP (const std::string &sceneName)"
.br
.RI "Unloads a scene\&. "
.ti -1c
.RI "bool \fBIsSceneReady\fP (const std::string &sceneName)"
.br
.RI "returns true if the scene in argument is ready to be used, false else "
.in -1c
.SH "Detailed Description"
.PP 
Singleton for the scene manager, which can be used to load scenes in the background and switch between them\&. 


.SH "Member Function Documentation"
.PP 
.SS "void eng::SceneManager::InitEditorMode ()"

.PP
Inits the editor mode of the scenemanager to allow for manual commands\&. 
.SS "bool eng::SceneManager::IsSceneReady (const std::string & sceneName)"

.PP
returns true if the scene in argument is ready to be used, false else 
.SS "void eng::SceneManager::LoadSceneAsync (const std::string & sceneName)"

.PP
Loads a scene in the background\&. 
.PP
\fBParameters\fP
.RS 4
\fIsceneName\fP 
.RE
.PP

.SS "void eng::SceneManager::SwitchScene (const std::string & sceneName)"

.PP
switches the current scene to the one specified 
.SS "void eng::SceneManager::UnloadScene (const std::string & sceneName)"

.PP
Unloads a scene\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
