.TH "eng::EngineException" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eng::EngineException
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEngineException\fP (const std::string &msg, const std::string &file, const std::string &function, int line)"
.br
.RI "Construct a new \fBEngine\fP Exception object while keeping track of the line at which the exception was thrown\&. "
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eng::EngineException::EngineException (const std::string & msg, const std::string & file, const std::string & function, int line)\fC [inline]\fP"

.PP
Construct a new \fBEngine\fP Exception object while keeping track of the line at which the exception was thrown\&. 
.PP
\fBParameters\fP
.RS 4
\fImsg\fP 
.br
\fIfile\fP 
.br
\fIfunction\fP 
.br
\fIline\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
