.TH "Focusable" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Focusable \- A class to manage globally the state of the focus of the application\&. For exemple if an object gets clicked on, it will be considered as being focused by the user\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Hoverable\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsFocused\fP (bool &target)"
.br
.ti -1c
.RI "static void \fBFocus\fP (bool &target)"
.br
.ti -1c
.RI "static void \fBUnFocus\fP (bool &target)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool * \fBFocusedElement\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to manage globally the state of the focus of the application\&. For exemple if an object gets clicked on, it will be considered as being focused by the user\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
