.TH "graph::vec4< T >" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph::vec4< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP = 0"
.br
.ti -1c
.RI "T \fBy\fP = 0"
.br
.ti -1c
.RI "T \fBz\fP = 0"
.br
.ti -1c
.RI "T \fBw\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
