.TH "graph::graphText_t" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph::graphText_t \- Describes a text to be drawn on the window\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IGraphicalModule\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvec2f\fP \fBpos\fP = { 0, 0 }"
.br
.ti -1c
.RI "std::string \fBtext\fP = ''"
.br
.ti -1c
.RI "\fBvec4uc\fP \fBcolor\fP = { 0, 0, 0, 0 }"
.br
.ti -1c
.RI "float \fBfontSize\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes a text to be drawn on the window\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
