.TH "graph::vec2< T >" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph::vec2< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvec2\fP< T > \fBoperator+\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBoperator\-\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBoperator*\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBoperator/\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBoperator+\fP (const T &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBoperator\-\fP (const T &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBoperator*\fP (const T &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBoperator/\fP (const T &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > & \fBoperator+=\fP (const \fBvec2\fP< T > &other)"
.br
.ti -1c
.RI "\fBvec2\fP< T > & \fBoperator\-=\fP (const \fBvec2\fP< T > &other)"
.br
.ti -1c
.RI "\fBvec2\fP< T > & \fBoperator*=\fP (const \fBvec2\fP< T > &other)"
.br
.ti -1c
.RI "\fBvec2\fP< T > & \fBoperator/=\fP (const \fBvec2\fP< T > &other)"
.br
.ti -1c
.RI "\fBvec2\fP< T > & \fBoperator+=\fP (const T &other)"
.br
.ti -1c
.RI "\fBvec2\fP< T > & \fBoperator\-=\fP (const T &other)"
.br
.ti -1c
.RI "\fBvec2\fP< T > & \fBoperator*=\fP (const T &other)"
.br
.ti -1c
.RI "\fBvec2\fP< T > & \fBoperator/=\fP (const T &other)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const T &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const T &other) const"
.br
.ti -1c
.RI "float \fBmagnitude\fP () const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBnormalized\fP () const"
.br
.ti -1c
.RI "float \fBdot\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "float \fBdistance\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBlerp\fP (const \fBvec2\fP< T > &other, float t) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBreflect\fP (const \fBvec2\fP< T > &normal) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBproject\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBrotate\fP (float angle) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBrotateAround\fP (const \fBvec2\fP< T > &point, float angle) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBmin\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBmax\fP (const \fBvec2\fP< T > &other) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBclamp\fP (const \fBvec2\fP< T > &min, const \fBvec2\fP< T > &max) const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBabs\fP () const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBfloor\fP () const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBceil\fP () const"
.br
.ti -1c
.RI "\fBvec2\fP< T > \fBround\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP = 0"
.br
.ti -1c
.RI "T \fBy\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
