.TH "graph::Clickable" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph::Clickable \- Base class for objects that can be clicked\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Hoverable\&.hpp>\fP
.PP
Inherits \fBgraph::Hoverable\fP\&.
.PP
Inherited by \fBTextField\fP, and \fBUIButton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestClick\fP ()"
.br
.RI "Tests if the object has been clicked onto, and if so, plays the callback attached to the object\&. "
.ti -1c
.RI "void \fBSetClickable\fP (bool clickable)"
.br
.RI "Enables the clickable feature\&. "
.ti -1c
.RI "bool \fBIsClickable\fP () const"
.br
.RI "Returns whether the object is clickable or not\&. "
.ti -1c
.RI "void \fBSetClickCallback\fP (std::function< void()> callback)"
.br
.RI "Sets the callback to be played when the object is clicked\&. "
.in -1c

Public Member Functions inherited from \fBgraph::Hoverable\fP
.in +1c
.ti -1c
.RI "void \fBTestHover\fP ()"
.br
.ti -1c
.RI "void \fBSetHoverable\fP (bool hoverable)"
.br
.RI "Enables the hoverable feature\&. "
.ti -1c
.RI "bool \fBIsHoverable\fP () const"
.br
.RI "Returns whether the object is hoverable or not\&. "
.ti -1c
.RI "void \fBSetDiv\fP (\fBUIDiv\fP *div)"
.br
.RI "Sets the div to which the hoverable feature is attached\&. "
.ti -1c
.RI "void \fBSetHoverCallback\fP (std::function< void()> callback)"
.br
.RI "Sets the callback to be played when the object is hovered\&. "
.ti -1c
.RI "void \fBSetOnUnhoverCallback\fP (std::function< void()> callback)"
.br
.RI "Sets the callback to be played when the object is unhovered\&. "
.ti -1c
.RI "bool \fBIsHovered\fP ()"
.br
.RI "Returns whether the object is hovered or not\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_clickable\fP = true"
.br
.ti -1c
.RI "std::function< void()> \fBm_clickCallback\fP = nullptr"
.br
.in -1c

Protected Attributes inherited from \fBgraph::Hoverable\fP
.in +1c
.ti -1c
.RI "bool \fBm_hoverable\fP = true"
.br
.ti -1c
.RI "bool \fBm_isHovered\fP = false"
.br
.ti -1c
.RI "std::function< void()> \fBm_callback\fP = nullptr"
.br
.ti -1c
.RI "std::function< void()> \fBm_onUnhoverCallback\fP = nullptr"
.br
.ti -1c
.RI "\fBUIDiv\fP * \fBm_hoverDiv\fP = nullptr"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for objects that can be clicked\&. 


.SH "Member Function Documentation"
.PP 
.SS "bool graph::Clickable::IsClickable () const"

.PP
Returns whether the object is clickable or not\&. 
.PP
\fBReturns\fP
.RS 4
true 
.PP
false 
.RE
.PP

.SS "void graph::Clickable::SetClickable (bool clickable)"

.PP
Enables the clickable feature\&. 
.PP
\fBParameters\fP
.RS 4
\fIclickable\fP 
.RE
.PP

.SS "void graph::Clickable::SetClickCallback (std::function< void()> callback)"

.PP
Sets the callback to be played when the object is clicked\&. 
.PP
\fBParameters\fP
.RS 4
\fIdiv\fP 
.RE
.PP

.SS "void graph::Clickable::TestClick ()"

.PP
Tests if the object has been clicked onto, and if so, plays the callback attached to the object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
