.TH "InputManager::EventDescription" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputManager::EventDescription
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::function< bool(\fBEventInfo\fP &)> \fBtestTriggered\fP"
.br
.RI "The function to call to check if the event is triggered\&. If the function returns true, the event is triggered\&. If needed, fills the \fBEventInfo\fP structure with information about the event\&. All char pressed are consumed before this function is called, and can be retrieved using the WasCharPressed function\&. "
.ti -1c
.RI "std::function< void(\fBEventInfo\fP)> \fBonTriggerCallback\fP"
.br
.RI "The function to call when the event is triggered\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::function<void(\fBEventInfo\fP)> InputManager::EventDescription::onTriggerCallback"

.PP
The function to call when the event is triggered\&. 
.SS "std::function<bool(\fBEventInfo\fP&)> InputManager::EventDescription::testTriggered"

.PP
The function to call to check if the event is triggered\&. If the function returns true, the event is triggered\&. If needed, fills the \fBEventInfo\fP structure with information about the event\&. All char pressed are consumed before this function is called, and can be retrieved using the WasCharPressed function\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
