.TH "lib::LibUtils" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib::LibUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void * \fBgetLibHandle\fP (const std::string &path)"
.br
.ti -1c
.RI "static void * \fBgetSymHandle\fP (void *lib_handle, const std::string &sym_name)"
.br
.ti -1c
.RI "static void \fBcloseLibHandle\fP (void *lib_handle)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
