.TH "myposix::Poll" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myposix::Poll
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaPollfd\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBpoll\fP (std::vector< \fBaPollfd\fP > &fds, int timeout)"
.br
.ti -1c
.RI "static bool \fBisReadable\fP (\fBaPollfd\fP &fd)"
.br
.ti -1c
.RI "static void \fBinitSocket\fP (int &fd)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
