.TH "serv::ServerImpl::Message" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serv::ServerImpl::Message
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP (const std::string &data, int code=200)"
.br
.ti -1c
.RI "std::string \fBGetData\fP () const"
.br
.RI "Returns the string of the message\&. "
.ti -1c
.RI "std::time_t \fBGetTime\fP () const"
.br
.RI "Returns the time at which the message was created\&. "
.ti -1c
.RI "int \fBGetCode\fP () const"
.br
.RI "Get the status of the message\&. (for exemple if a request is ok, the status will be 200) "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBMessage\fP \fBWaitingForHandshake\fP = \fBMessage\fP('Connection OK, waiting for handshake\&.', 0)"
.br
.ti -1c
.RI "static const \fBMessage\fP \fBHandshakeOK\fP = \fBMessage\fP('Handshake OK', 0)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int serv::ServerImpl::Message::GetCode () const"

.PP
Get the status of the message\&. (for exemple if a request is ok, the status will be 200) 
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP

.SS "std::string serv::ServerImpl::Message::GetData () const"

.PP
Returns the string of the message\&. 
.PP
\fBReturns\fP
.RS 4
std::string 
.RE
.PP

.SS "std::time_t serv::ServerImpl::Message::GetTime () const"

.PP
Returns the time at which the message was created\&. 
.PP
\fBReturns\fP
.RS 4
std::time_t 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
