.TH "serv::ServerImpl::IClient" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serv::ServerImpl::IClient \- This \fBIClient\fP interface is used to represent a distant client and store its associated data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Server\&.hpp>\fP
.PP
Inherited by \fBTestClient\fP, and \fBTestClient2\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBMessage\fP \fBHandleRequest\fP (const std::string &data)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
This \fBIClient\fP interface is used to represent a distant client and store its associated data\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
