.TH "serv::ServerImpl::ClientBucket" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serv::ServerImpl::ClientBucket \- Encapsulates a client and its associated data\&. It provides handles to send and receive data from the client, as well as an instance of an \fBIClient\fP which will handle the reveived requests\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Server\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClientBucket\fP (int port)"
.br
.ti -1c
.RI "void \fBSetClient\fP (std::shared_ptr< \fBIClient\fP > client)"
.br
.ti -1c
.RI "void \fBSend\fP (const std::string &data)"
.br
.ti -1c
.RI "void \fBReceive\fP (const std::string &data)"
.br
.ti -1c
.RI "std::shared_ptr< \fBIClient\fP > \fBGetClient\fP () const"
.br
.ti -1c
.RI "int \fBGetSocket\fP () const"
.br
.ti -1c
.RI "\fBClientBucket\fP & \fBoperator<<\fP (const \fBMessage\fP &message)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > static std::shared_ptr< \fBIClient\fP > \fBGenerateClient\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Encapsulates a client and its associated data\&. It provides handles to send and receive data from the client, as well as an instance of an \fBIClient\fP which will handle the reveived requests\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
