.TH "Sprite" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSprite\fP (const std::string &path)"
.br
.ti -1c
.RI "void \fBDraw\fP ()"
.br
.ti -1c
.RI "Rectangle & \fBGetRect\fP ()"
.br
.ti -1c
.RI "Vector2 & \fBGetOrigin\fP ()"
.br
.ti -1c
.RI "Vector2 & \fBGetScale\fP ()"
.br
.ti -1c
.RI "float & \fBGetRotation\fP ()"
.br
.ti -1c
.RI "Color & \fBGetColor\fP ()"
.br
.ti -1c
.RI "bool & \fBGetFlipX\fP ()"
.br
.ti -1c
.RI "bool & \fBGetFlipY\fP ()"
.br
.ti -1c
.RI "std::string & \fBGetPath\fP ()"
.br
.ti -1c
.RI "void \fBSetRect\fP (const Rectangle &rect)"
.br
.ti -1c
.RI "void \fBSetOrigin\fP (const Vector2 &origin)"
.br
.ti -1c
.RI "void \fBSetScale\fP (const Vector2 &scale)"
.br
.ti -1c
.RI "void \fBSetRotation\fP (float rotation)"
.br
.ti -1c
.RI "void \fBSetColor\fP (const Color &color)"
.br
.ti -1c
.RI "void \fBSetFlipX\fP (bool flipX)"
.br
.ti -1c
.RI "void \fBSetFlipY\fP (bool flipY)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
