.TH "td::ThreadedQueue< threadCount >" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
td::ThreadedQueue< threadCount >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Func , typename\&.\&.\&. Args> void \fBPush\fP (Func func, Args\&.\&.\&. args)"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
