.TH "TestClient2" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestClient2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBserv::ServerImpl::IClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBserv::ServerImpl::Message\fP \fBHandleRequest\fP (const std::string &data) override"
.br
.in -1c
.in +1c
.ti -1c
.RI "virtual \fBMessage\fP \fBHandleRequest\fP (const std::string &data)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBserv::ServerImpl::Message\fP TestClient2::HandleRequest (const std::string & data)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBserv::ServerImpl::IClient\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
