.TH "ui::UIManager::Button" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui::UIManager::Button
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBtext\fP"
.br
.ti -1c
.RI "Vector2 \fBposition\fP"
.br
.ti -1c
.RI "int \fBfontSize\fP"
.br
.ti -1c
.RI "Color \fBtextColor\fP = BLACK"
.br
.ti -1c
.RI "Color \fBcolorDefault\fP = GRAY"
.br
.ti -1c
.RI "Color \fBcolorHover\fP = DARKGRAY"
.br
.ti -1c
.RI "Color \fBcolorPressed\fP = YELLOW"
.br
.ti -1c
.RI "bool \fBpressed\fP = false"
.br
.ti -1c
.RI "std::function< void()> \fBcallback\fP = []() {}"
.br
.ti -1c
.RI "int \fBlayer\fP = DEFAULT_TEXT_LAYER"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
