.TH "UIScrollableList" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIScrollableList
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnAddComponent\fP (int entityID)"
.br
.ti -1c
.RI "void \fBDraw\fP ()"
.br
.ti -1c
.RI "void \fBSetHeight\fP (int height)"
.br
.ti -1c
.RI "void \fBAddOptions\fP (std::map< std::string, Action > options)"
.br
.ti -1c
.RI "void \fBSetPosition\fP (\fBgraph::vec2f\fP pos)"
.br
.ti -1c
.RI "std::map< std::string, Action > \fBGetOptions\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
