.TH "wow::WowGraphicsEngine" 3 "Mon Dec 18 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wow::WowGraphicsEngine
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBWowGraphicsEngine\fP > \fBGet\fP ()"
.br
.ti -1c
.RI "void \fBInitWowGraphicsEngine\fP ()"
.br
.RI "Starts the mode for rendering 3D objects using voxel graphics and raymarching\&. "
.ti -1c
.RI "void \fBStartRenderMode\fP ()"
.br
.ti -1c
.RI "void \fBEndRenderMode\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBEnable\fP ()"
.br
.RI "Enables the \fBWowGraphicsEngine\fP pipeline\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::shared_ptr< \fBWowGraphicsEngine\fP > \fBInstance\fP = nullptr"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void wow::WowGraphicsEngine::Enable ()\fC [static]\fP"

.PP
Enables the \fBWowGraphicsEngine\fP pipeline\&. 
.SS "void wow::WowGraphicsEngine::InitWowGraphicsEngine ()"

.PP
Starts the mode for rendering 3D objects using voxel graphics and raymarching\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
