name: Repository Mirroring

on: [push]

env:
  TARGET_REPOSITORY: git@github.com:EpitechPromo2026/B-CPP-500-BAR-5-2-rtype-eliot.janvier.git

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build_and_mirror:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Repository Mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repository: ${{ env.TARGET_REPOSITORY }}
          target_token: ${{ secrets.EPITECH_SSH_MIRROR_PRIVATE_KEY }}
