name: Repository Mirroring

on: [push]
# on:
#   push:
#     branches:
#       - master

env:
  TARGET_REPOSITORY: git@github.com:EpitechPromo2026/B-CPP-500-BAR-5-2-rtype-eliot.janvier.git

jobs:
  build_fedora:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
      - run: ./fast build


  build_windows:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
        - run: ./fast build

  build_and_mirror:
    runs-on: ubuntu-latest
    needs: [build_fedora, build_windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Mirror repository
      #   uses: pixta-dev/repository-mirroring-action@v1
      #   with:
      #     ssh_private_key: ${{ secrets.EPITECH_PRIVATE_SSH }}
      #     target_repo_url: ${{ env.TARGET_REPOSITORY }}