name: Repository Mirroring

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TARGET_REPOSITORY: git@github.com:EpitechPromo2026/B-CPP-500-BAR-5-2-rtype-eliot.janvier.git

jobs:
  build_fedora:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global --add safe.directory '*'
      # install doxygen
      - run: sudo dnf -y install doxygen
      - run: ./fast build -j10
      - run: cd build ; ctest
      - run: cd build && make doc 
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts && cat ~/.ssh/known_hosts
      - run: |
          cd build/docs/rengine.github.io
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Documentation update"
          git push https::${{ secrets.GITHUB_TOKEN }}@github.com/EpitechPromo2026/B-CPP-500-BAR-5-2-rtype-eliot.janvier.git HEAD:main

  build_windows:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2
        - run: git config --global --add safe.directory '*'
        - run: ./fast build

  # post_documentation:
  #   runs-on: ubuntu-latest
  #   needs: [build_fedora]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - run: git config --global --add safe.directory '*'
  #     - run: cd build && make doc
  #     -
      
  build_and_mirror:
    runs-on: ubuntu-latest
    needs: [build_fedora]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          ssh_private_key: ${{ secrets.EPITECH_PRIVATE_SSH }}
          target_repo_url: ${{ env.TARGET_REPOSITORY }}